name: dataplane

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: dataplane
      POSTGRES_PASSWORD: dataplane
      POSTGRES_DB: dataplane
    ports:
      - "${POSTGRES_PORT:-55432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataplane -d dataplane"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgres://dataplane:dataplane@postgres:5432/dataplane?sslmode=disable
      PROVISIONER: mock
      WORKERS: 4
      FAILURE_INJECTION_ATTEMPTS: ${FAILURE_INJECTION_ATTEMPTS:-0}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v3.5.0
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  pgdata:
