apiVersion: v1
kind: Namespace
metadata:
  name: dataplane-clusters
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataplane-control-plane
  namespace: dataplane-clusters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataplane-control-plane
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "pods", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataplane-control-plane
subjects:
  - kind: ServiceAccount
    name: dataplane-control-plane
    namespace: dataplane-clusters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dataplane-control-plane
