syntax = "proto3";

package dataplane.v1;

option go_package = "github.com/SaiVyshnavi1522/dataplane-control-plane/gen/dataplane/v1;dataplanev1";

import "google/protobuf/timestamp.proto";

service ClusterService {
  rpc CreateCluster(CreateClusterRequest) returns (CreateClusterResponse);
  rpc GetCluster(GetClusterRequest) returns (Cluster);
  rpc ListClusters(ListClustersRequest) returns (ListClustersResponse);
  rpc ScaleCluster(ScaleClusterRequest) returns (Cluster);
  rpc DeleteCluster(DeleteClusterRequest) returns (Cluster);
}

message CreateClusterRequest {
  string idempotency_key = 1;
  string name = 2;
  string engine = 3;
  string version = 4;
  int32 nodes = 5;
}

message CreateClusterResponse {
  Cluster cluster = 1;
  bool reused = 2;
}

message GetClusterRequest {
  string id = 1;
}

message ListClustersRequest {}

message ListClustersResponse {
  repeated Cluster clusters = 1;
}

message ScaleClusterRequest {
  string id = 1;
  int32 nodes = 2;
}

message DeleteClusterRequest {
  string id = 1;
}

message Cluster {
  string id = 1;
  string name = 2;
  string engine = 3;
  string version = 4;
  int32 desired_nodes = 5;
  ClusterStatus status = 6;
  string last_error = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}

enum ClusterStatus {
  CLUSTER_STATUS_UNSPECIFIED = 0;
  CLUSTER_STATUS_REQUESTED = 1;
  CLUSTER_STATUS_PROVISIONING = 2;
  CLUSTER_STATUS_RUNNING = 3;
  CLUSTER_STATUS_SCALING = 4;
  CLUSTER_STATUS_DELETING = 5;
  CLUSTER_STATUS_DELETED = 6;
  CLUSTER_STATUS_FAILED = 7;
}
